name: Clean code check
on:
  push:
    branches:
      - main

jobs:
  PMD-Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: pmd/pmd-github-action@v2
        with:
          rulesets: 'ruleset.xml'